thales-markets/contracts

contracts/ThalesRoyale/ThalesRoyale.sol, scripts/abi/ThalesRoyale.json, test/contracts/ThalesRoyale/royale.js
Adding properties for eliminated and total players per round
=> Adding properties for eliminated and total players per round

contracts/ThalesRoyale/ThalesRoyale.sol, test/contracts/ThalesRoyale/royale.js
https://thalesmarket.atlassian.net/browse/TD-129
=> last man standing

scripts/deployThalesRoyale/deployThalesRoyale.js
3 days -> sign up
24 hours -> round length
6 -> rounds
8 hours -> choose positions 
npx hardhat run --network optimisticKovan scripts/deployThalesRoyale/deployThalesRoyale.js
=> Prepare for deploy

scripts/deployThalesRoyale/deprecated/deployThalesRoyale.js, scripts/deployThalesRoyale/forDevelopment/interractThalesRoyale.js, scripts/deployThalesRoyale/thalesRoyale/deployRoyale.js, scripts/deployThalesRoyale/thalesRoyale/upgradeRoyale.js, scripts/deployThalesRoyale/thalesRoyalePrivateRooms/deployThalesRoyalePrivateRoom.js
=> Reorganize folder structure for royale

contracts/ThalesRoyale/ThalesRoyale.sol
=> small typo fix

contracts/ThalesRoyale/ThalesRoyale.sol, scripts/abi/ThalesRoyale.json, scripts/deployThalesRoyale/thalesRoyale/changeSafeBoxRoyaleSeason.js, test/contracts/ThalesRoyale/royale.js
Provided safebox and safebox impact calculation
it is a percentage of an amount 
TODO:
=> Royale safeBox and safeBoxImpact

.openzeppelin/unknown-69.json, contracts/EscrowAndStaking/EscrowThales.sol, contracts/EscrowAndStaking/StakingThales.sol, scripts/abi/StakingThales.json, scripts/deployEscrowAndStaking/deploy_StakingRewards.js, scripts/deployEscrowAndStaking/update_addresses_on_Staking.js, scripts/deployEscrowAndStaking/verifyOnly_Staking_Escrow.js, scripts/deployments.json
=> ThalesStakingRewardsPool deployed

.openzeppelin/unknown-10.json, scripts/deployments.json
=> deploy OP royale

scripts/deployEscrowAndStaking/update_addresses_on_Staking.js
- Address already set on OP deployment
- In case we repeat deployment, to avoid issues
=> - uncommented ThalesRoyale setter - already set on OP deployment

scripts/deployThalesRoyale/thalesRoyale/upgradeRoyale.js
Only needed is `ProxyAdmin.upgrade(proxy, impl);`
=> prepareUpgrade into upgrade script

contracts/ExoticPositionalMarkets/ExoticPositionalFixedMarket.sol, contracts/ExoticPositionalMarkets/ExoticPositionalMarketManager.sol, contracts/ExoticPositionalMarkets/ExoticPositionalOpenBidMarket.sol, contracts/ExoticPositionalMarkets/ThalesOracleCouncil.sol, scripts/deployments.json
- Claiming fees event
- Withdrawals period adjusted
=> Fixed market mastercopy updated

test/contracts/ThalesRoyale/royalePassport.js
=> update code coverage

.openzeppelin/kovan.json, codecov.yml, contracts/SportMarkets/Rundown/TherundownConsumer.sol, scripts/deployments.json, test/contracts/SportMarkets/TherundownConsumer.js
Adding possibility for cancel when draw or no contest of UFC event is happened
=> Adding draw or no contest for UFC events

.openzeppelin/kovan.json, contracts/SportMarkets/Rundown/TherundownConsumer.sol, scripts/deployments.json, test/contracts/SportMarkets/TherundownConsumer.js
when fulfillResolved happens- need to pause if the start time of a game is in the future if it is passed cancel
also, when manual resolve or cancel unpause market for user can claim
=> Bug fixing automatically pause/cancel and unpause on manual

contracts/SportMarkets/Rundown/TherundownConsumer.sol
Here is a warning:
Same ABI, so deployment will pick up in next iteration
=> gameCreated is global variable warning of shadowing

contracts/AMM/ThalesAMM.sol, contracts/AMM/ThalesAMMNew.sol, scripts/abi/ThalesAMM.json, scripts/abi/ThalesAMMNew.json, test/contracts/ThalesAMM/thalesAmmTIP101FixForDiscounts.js, test/contracts/ThalesAMMNew/thalesAmmTIP101FixForDiscounts.js
A fix to not show max discount when one side is out of liquidity due to price limits
=> TIP-101: fix for discounts

.openzeppelin/unknown-42161.json, contracts/SportMarkets/SportPositions/SportPositionalMarketManager.sol, contracts/utils/MultiSend.sol, scripts/abi/MultiSend.json, scripts/deploySportMarkets/deploySportPositionalMarkets/fund_SportPositionalMarkets.js, scripts/deployments.json, test/contracts/SportMarkets/ParlayAMM_Arbi.js
- fix for Arbitrum rounding error
- fix in Manager
=> - fix for rounding error on Arbitrum

contracts/SportMarkets/SportsAMM.sol
- modifications to useMinSpread on buyQuote
- use spreadPerAddress for buyFromAMM
=> Modifications for minSpread on SportsAMM

.openzeppelin/unknown-10.json, .openzeppelin/unknown-137.json, .openzeppelin/unknown-42161.json, .openzeppelin/unknown-56.json, .openzeppelin/unknown-8453.json, contracts/SpeedMarkets/MultiCollateralOnOffRamp.sol, contracts/SpeedMarkets/SpeedMarketsAMM.sol, scripts/deploySpeedMarkets/upgradeSpeedAMM.js, scripts/deployments.json
fix risk per asset calculation
=> Speed markets cleansed

contracts/SportMarkets/Parlay/ParlayVerifier.sol, contracts/SportMarkets/SportAMMRiskManager.sol
- block a parlay if at least one market has 0 odds
- return 0 for cap in RiskManager if a match has already started
=> added checks

contracts/SportMarkets/SportsAMM.sol, scripts/abi/SportsAMM.json
added discount event (same as in thalesAMM)
=> added discount event

contracts/EscrowAndStaking/StakingThales.sol, contracts/interfaces/IStakingThales.sol, package.json
publish the change to allow calling update volume with a different number of decimals for collateral
=> Extend staking thales

contracts/SpeedMarkets/MultiCollateralOnOffRamp.sol
use param instead of state variable
=> wrong param was checked - fixed

.openzeppelin/unknown-42161.json, .openzeppelin/unknown-8453.json, contracts/AMM/SafeBoxBuyback.sol, scripts/abi/SafeBoxBuyback.json, scripts/deployAMM/SafeBox/upgradeSafeBoxBuyback.js, scripts/deployments.json
Add function to retreive WETH from SafeBoxBuyback
=> Retreive WETH from SafeBoxBuyback
